version: "3.4"

x-base: &base
  build:
    context: ./app
    dockerfile: Dockerfile
  env_file: 
    - .env
  depends_on:
    - redis

services:
  app:
    <<: *base
    ports:
     - "5001:5000"
    command: >
      sh -c "python app.py"

  celery_beat:
    <<: *base
    depends_on:
      - app
    command: >
      sh -c "celery beat -A app.celery --schedule=/tmp/celerybeat-schedule --loglevel=INFO --pidfile=/tmp/celerybeat.pid"

  celery:
    <<: *base
    depends_on:
      - app
    command: >
      sh -c "celery worker -A app.celery --loglevel=info"

  redis:
    image: redis
